services:
  db-backup:
    init: true
    build:
      context: ./db_backup
    container_name: ${PROJECT_NAME}_db_backup
    env_file:
      - ./envs/.db_backup.env
    volumes:
      - ./volumes/db_backup:/backup
      - ./db_backup/backup.sh:/scripts/backup.sh
      - ./envs/.db_backup.env:/scripts/.env
      - ./db_backup/cron.tab:/etc/cron.d/cron.tab
      - ./volumes/logs/db_backup:/logs:rw
    networks:
      - net
    restart: always
