"""empty message

Revision ID: 0b43142d1529
Revises: 008c63a43270
Create Date: 2025-11-13 10:24:09.087580

"""

from typing import Sequence, Union
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "0b43142d1529"
down_revision: Union[str, None] = "008c63a43270"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("project_wiki_attachment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_project_wiki_attachment_wiki_id"))
        batch_op.alter_column("wiki_id", new_column_name="project_wiki_id")

    with op.batch_alter_table("project_wiki_attachment", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_project_wiki_attachment_project_wiki_id"), ["project_wiki_id"], unique=False
        )
        batch_op.create_foreign_key(
            batch_op.f("FK_project_wiki_attachment_project_wiki"),
            "project_wiki",
            ["project_wiki_id"],
            ["id"],
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("project_wiki_attachment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_project_wiki_attachment_project_wiki_id"))
        batch_op.alter_column("project_wiki_id", new_column_name="wiki_id")

    with op.batch_alter_table("project_wiki_attachment", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_project_wiki_attachment_wiki_id"), ["wiki_id"], unique=False)
        batch_op.create_foreign_key(
            batch_op.f("FK_project_wiki_attachment_project_wiki"),
            "project_wiki",
            ["wiki_id"],
            ["id"],
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###
