"""empty message

Revision ID: ca34731e2432
Revises: 77d5a4d6c4ba
Create Date: 2025-11-21 19:57:03.424562

"""

from typing import Sequence, Union
import sqlalchemy as sa
from alembic import op
from langboard_shared.core.db.ColumnTypes import SnowflakeIDType


# revision identifiers, used by Alembic.
revision: str = "ca34731e2432"
down_revision: Union[str, None] = "77d5a4d6c4ba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_chat_session",
        sa.Column("id", SnowflakeIDType, nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("chat_session_id", SnowflakeIDType, nullable=True),
        sa.Column("project_id", SnowflakeIDType, nullable=False),
        sa.ForeignKeyConstraint(["chat_session_id"], ["chat_session.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("project_chat_session", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_project_chat_session_chat_session_id"), ["chat_session_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_project_chat_session_project_id"), ["project_id"], unique=False)

    with op.batch_alter_table("chat_session", schema=None) as batch_op:
        batch_op.drop_column("filterable_id")
        batch_op.drop_column("filterable_table")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chat_session", schema=None) as batch_op:
        batch_op.add_column(sa.Column("filterable_table", sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column("filterable_id", sa.BIGINT(), nullable=True))

    with op.batch_alter_table("project_chat_session", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_project_chat_session_project_id"))
        batch_op.drop_index(batch_op.f("ix_project_chat_session_chat_session_id"))

    op.drop_table("project_chat_session")
    # ### end Alembic commands ###
