"""empty message

Revision ID: 008c63a43270
Revises: 825f7dc919c3
Create Date: 2025-11-11 20:06:47.066413

"""

from typing import Sequence, Union
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "008c63a43270"
down_revision: Union[str, None] = "825f7dc919c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("project_role", schema=None) as batch_op:
        batch_op.alter_column("user_id", existing_type=sa.BIGINT(), nullable=False)
        batch_op.create_index(batch_op.f("ix_project_role_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("project_role", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_project_role_user_id"))
        batch_op.alter_column("user_id", existing_type=sa.BIGINT(), nullable=True)

    # ### end Alembic commands ###
