"""empty message

Revision ID: 66efd75acee4
Revises: c192eeaf2635
Create Date: 2025-10-09 13:26:12.009514

"""

from typing import Sequence, Union
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes
from alembic import op
from langboard_shared.core.db.ColumnTypes import SnowflakeIDType


# revision identifiers, used by Alembic.
revision: str = "c09218ff8145"
down_revision: Union[str, None] = "c192eeaf2635"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_session",
        sa.Column("id", SnowflakeIDType, nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("filterable_table", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("filterable_id", SnowflakeIDType, nullable=True),
        sa.Column("user_id", SnowflakeIDType, nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("last_messaged_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("chat_session", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_chat_session_user_id"), ["user_id"], unique=False)

    with op.batch_alter_table("chat_history", schema=None) as batch_op:
        batch_op.add_column(sa.Column("chat_session_id", SnowflakeIDType, nullable=True))
        batch_op.add_column(sa.Column("is_received", sa.Boolean(), nullable=False, server_default="0"))
        batch_op.create_index(batch_op.f("ix_chat_history_chat_session_id"), ["chat_session_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_chat_history_is_received"), ["is_received"], unique=False)
        batch_op.create_foreign_key(
            batch_op.f("FK_chat_history_chat_session"), "chat_session", ["chat_session_id"], ["id"], ondelete="CASCADE"
        )
        batch_op.drop_column("filterable_table")
        batch_op.drop_column("receiver_id")
        batch_op.drop_column("filterable_id")
        batch_op.drop_column("sender_id")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chat_history", schema=None) as batch_op:
        batch_op.add_column(sa.Column("sender_id", sa.BIGINT(), nullable=True))
        batch_op.add_column(sa.Column("filterable_id", sa.BIGINT(), nullable=True))
        batch_op.add_column(sa.Column("receiver_id", sa.BIGINT(), nullable=True))
        batch_op.add_column(sa.Column("filterable_table", sa.VARCHAR(), nullable=False, server_default=""))
        batch_op.create_foreign_key(
            batch_op.f("FK_chat_history_user_2"), "user", ["receiver_id"], ["id"], ondelete="CASCADE"
        )
        batch_op.create_foreign_key(
            batch_op.f("FK_chat_history_user"), "user", ["sender_id"], ["id"], ondelete="CASCADE"
        )
        batch_op.drop_index(batch_op.f("ix_chat_history_is_received"))
        batch_op.drop_index(batch_op.f("ix_chat_history_chat_session_id"))
        batch_op.drop_column("is_received")
        batch_op.drop_column("chat_session_id")

    with op.batch_alter_table("chat_session", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_chat_session_user_id"))

    op.drop_table("chat_session")
    # ### end Alembic commands ###
