"""empty message

Revision ID: 825f7dc919c3
Revises: fc816dc03d6d
Create Date: 2025-10-23 20:54:30.603466

"""

from typing import Sequence, Union
import sqlalchemy as sa
from alembic import op
from langboard_shared.core.db.ColumnTypes import CSVType, SnowflakeIDType
from langboard_shared.models.bases.BaseBotScopeModel import BotTriggerCondition


# revision identifiers, used by Alembic.
revision: str = "825f7dc919c3"
down_revision: Union[str, None] = "fc816dc03d6d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_bot_log",
        sa.Column("id", SnowflakeIDType, nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("bot_log_id", SnowflakeIDType, nullable=True),
        sa.Column("project_id", SnowflakeIDType, nullable=False),
        sa.ForeignKeyConstraint(["bot_log_id"], ["bot_log.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("project_bot_log", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_project_bot_log_bot_log_id"), ["bot_log_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_project_bot_log_project_id"), ["project_id"], unique=False)

    op.create_table(
        "project_bot_schedule",
        sa.Column("id", SnowflakeIDType, nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("bot_schedule_id", SnowflakeIDType, nullable=False),
        sa.Column("project_id", SnowflakeIDType, nullable=False),
        sa.ForeignKeyConstraint(["bot_schedule_id"], ["bot_schedule.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("project_bot_schedule", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_project_bot_schedule_bot_schedule_id"), ["bot_schedule_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_project_bot_schedule_project_id"), ["project_id"], unique=False)

    op.create_table(
        "project_bot_scope",
        sa.Column("id", SnowflakeIDType, nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("bot_id", SnowflakeIDType, nullable=True),
        sa.Column("conditions", CSVType(BotTriggerCondition), nullable=False),
        sa.Column("project_id", SnowflakeIDType, nullable=False),
        sa.ForeignKeyConstraint(["bot_id"], ["bot.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("project_bot_scope", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_project_bot_scope_bot_id"), ["bot_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_project_bot_scope_project_id"), ["project_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("project_bot_scope", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_project_bot_scope_project_id"))
        batch_op.drop_index(batch_op.f("ix_project_bot_scope_bot_id"))

    op.drop_table("project_bot_scope")
    with op.batch_alter_table("project_bot_schedule", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_project_bot_schedule_project_id"))
        batch_op.drop_index(batch_op.f("ix_project_bot_schedule_bot_schedule_id"))

    op.drop_table("project_bot_schedule")
    with op.batch_alter_table("project_bot_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_project_bot_log_project_id"))
        batch_op.drop_index(batch_op.f("ix_project_bot_log_bot_log_id"))

    op.drop_table("project_bot_log")
    # ### end Alembic commands ###
