"""empty message

Revision ID: 77d5a4d6c4ba
Revises: 0b43142d1529
Create Date: 2025-11-20 06:05:32.883954

"""

from typing import Sequence, Union
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "77d5a4d6c4ba"
down_revision: Union[str, None] = "0b43142d1529"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("card_bot_schedule", schema=None) as batch_op:
        batch_op.add_column(sa.Column("last_rnu_at", sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table("project_bot_schedule", schema=None) as batch_op:
        batch_op.add_column(sa.Column("last_rnu_at", sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table("project_column_bot_schedule", schema=None) as batch_op:
        batch_op.add_column(sa.Column("last_rnu_at", sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("project_column_bot_schedule", schema=None) as batch_op:
        batch_op.drop_column("last_rnu_at")

    with op.batch_alter_table("project_bot_schedule", schema=None) as batch_op:
        batch_op.drop_column("last_rnu_at")

    with op.batch_alter_table("card_bot_schedule", schema=None) as batch_op:
        batch_op.drop_column("last_rnu_at")

    # ### end Alembic commands ###
