"""empty message

Revision ID: fc816dc03d6d
Revises: c09218ff8145
Create Date: 2025-10-22 21:39:31.863555

"""

from typing import Sequence, Union
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "fc816dc03d6d"
down_revision: Union[str, None] = "c09218ff8145"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("internal_bot", schema=None) as batch_op:
        batch_op.alter_column("url", new_column_name="api_url")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("internal_bot", schema=None) as batch_op:
        batch_op.alter_column("api_url", new_column_name="url")

    # ### end Alembic commands ###
