"""empty message

Revision ID: ddab3d9bf214
Revises: 65fe2891b018
Create Date: 2026-03-14 18:24:45.265433

"""

from typing import Sequence, Union
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes
from alembic import op
from langboard_shared.core.db.ColumnTypes import CSVType, SnowflakeIDType
from langboard_shared.domain.models.bases.BotTriggerCondition import BotTriggerCondition


# revision identifiers, used by Alembic.
revision: str = "ddab3d9bf214"
down_revision: Union[str, None] = "65fe2891b018"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bot_default_scope_branch",
        sa.Column("id", SnowflakeIDType, nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("bot_id", SnowflakeIDType, nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(["bot_id"], ["bot.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("bot_default_scope_branch", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_bot_default_scope_branch_bot_id"), ["bot_id"], unique=False)

    op.create_table(
        "card_bot_default_scope",
        sa.Column("id", SnowflakeIDType, nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("bot_default_scope_branch_id", SnowflakeIDType, nullable=True),
        sa.Column("conditions", CSVType(BotTriggerCondition), nullable=False),
        sa.ForeignKeyConstraint(["bot_default_scope_branch_id"], ["bot_default_scope_branch.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("card_bot_default_scope", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_card_bot_default_scope_bot_default_scope_branch_id"),
            ["bot_default_scope_branch_id"],
            unique=False,
        )

    op.create_table(
        "project_bot_default_scope",
        sa.Column("id", SnowflakeIDType, nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("bot_default_scope_branch_id", SnowflakeIDType, nullable=True),
        sa.Column("conditions", CSVType(BotTriggerCondition), nullable=False),
        sa.ForeignKeyConstraint(["bot_default_scope_branch_id"], ["bot_default_scope_branch.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("project_bot_default_scope", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_project_bot_default_scope_bot_default_scope_branch_id"),
            ["bot_default_scope_branch_id"],
            unique=False,
        )

    op.create_table(
        "project_column_bot_default_scope",
        sa.Column("id", SnowflakeIDType, nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("bot_default_scope_branch_id", SnowflakeIDType, nullable=True),
        sa.Column("conditions", CSVType(BotTriggerCondition), nullable=False),
        sa.ForeignKeyConstraint(["bot_default_scope_branch_id"], ["bot_default_scope_branch.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("project_column_bot_default_scope", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_project_column_bot_default_scope_bot_default_scope_branch_id"),
            ["bot_default_scope_branch_id"],
            unique=False,
        )

    with op.batch_alter_table("card_bot_scope", schema=None) as batch_op:
        batch_op.add_column(sa.Column("default_scope_branch_id", SnowflakeIDType, nullable=True))
        batch_op.create_index(
            batch_op.f("ix_card_bot_scope_default_scope_branch_id"), ["default_scope_branch_id"], unique=False
        )
        batch_op.create_foreign_key(
            batch_op.f("FK_card_bot_scope_bot_default_scope_branch_id"),
            "bot_default_scope_branch",
            ["default_scope_branch_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("project_bot_scope", schema=None) as batch_op:
        batch_op.add_column(sa.Column("default_scope_branch_id", SnowflakeIDType, nullable=True))
        batch_op.create_index(
            batch_op.f("ix_project_bot_scope_default_scope_branch_id"), ["default_scope_branch_id"], unique=False
        )
        batch_op.create_foreign_key(
            batch_op.f("FK_project_bot_scope_bot_default_scope_branch_id"),
            "bot_default_scope_branch",
            ["default_scope_branch_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("project_column_bot_scope", schema=None) as batch_op:
        batch_op.add_column(sa.Column("default_scope_branch_id", SnowflakeIDType, nullable=True))
        batch_op.create_index(
            batch_op.f("ix_project_column_bot_scope_default_scope_branch_id"), ["default_scope_branch_id"], unique=False
        )
        batch_op.create_foreign_key(
            batch_op.f("FK_project_column_bot_scope_bot_default_scope_branch_id"),
            "bot_default_scope_branch",
            ["default_scope_branch_id"],
            ["id"],
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("project_column_bot_scope", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("FK_project_column_bot_scope_bot_default_scope_branch_id"), type_="foreignkey"
        )
        batch_op.drop_index(batch_op.f("ix_project_column_bot_scope_default_scope_branch_id"))
        batch_op.drop_column("default_scope_branch_id")

    with op.batch_alter_table("project_bot_scope", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("FK_project_bot_scope_bot_default_scope_branch_id"), type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_project_bot_scope_default_scope_branch_id"))
        batch_op.drop_column("default_scope_branch_id")

    with op.batch_alter_table("card_bot_scope", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("FK_card_bot_scope_bot_default_scope_branch_id"), type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_card_bot_scope_default_scope_branch_id"))
        batch_op.drop_column("default_scope_branch_id")

    with op.batch_alter_table("project_column_bot_default_scope", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_project_column_bot_default_scope_bot_default_scope_branch_id"))

    op.drop_table("project_column_bot_default_scope")
    with op.batch_alter_table("project_bot_default_scope", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_project_bot_default_scope_bot_default_scope_branch_id"))

    op.drop_table("project_bot_default_scope")
    with op.batch_alter_table("card_bot_default_scope", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_card_bot_default_scope_bot_default_scope_branch_id"))

    op.drop_table("card_bot_default_scope")
    with op.batch_alter_table("bot_default_scope_branch", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bot_default_scope_branch_bot_id"))

    op.drop_table("bot_default_scope_branch")
    # ### end Alembic commands ###
