"""empty message

Revision ID: 65fe2891b018
Revises: 40cf298bc4f2
Create Date: 2026-03-03 16:46:12.615403

"""

from typing import Sequence, Union
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes
from alembic import op
from langboard_shared.core.db.ColumnTypes import CSVType, SnowflakeIDType


# revision identifiers, used by Alembic.
revision: str = "65fe2891b018"
down_revision: Union[str, None] = "40cf298bc4f2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "webhook_setting",
        sa.Column("id", SnowflakeIDType, nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("url", sa.TEXT(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("total_used_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "api_key_role",
        sa.Column("id", SnowflakeIDType, nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("actions", CSVType(str), nullable=False),
        sa.Column("user_id", SnowflakeIDType, nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("api_key_role", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_api_key_role_user_id"), ["user_id"], unique=False)

    op.create_table(
        "mcp_role",
        sa.Column("id", SnowflakeIDType, nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("actions", CSVType(str), nullable=False),
        sa.Column("user_id", SnowflakeIDType, nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("mcp_role", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_mcp_role_user_id"), ["user_id"], unique=False)

    op.create_table(
        "setting_role",
        sa.Column("id", SnowflakeIDType, nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("actions", CSVType(str), nullable=False),
        sa.Column("user_id", SnowflakeIDType, nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("setting_role", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_setting_role_user_id"), ["user_id"], unique=False)

    op.drop_table("app_setting", if_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("setting_role", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_setting_role_user_id"))

    op.drop_table("setting_role")
    with op.batch_alter_table("mcp_role", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_mcp_role_user_id"))

    op.drop_table("mcp_role")
    with op.batch_alter_table("api_key_role", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_api_key_role_user_id"))

    op.drop_table("api_key_role")
    op.drop_table("webhook_setting")

    # ### end Alembic commands ###
