"""empty message

Revision ID: 40cf298bc4f2
Revises: ca34731e2432
Create Date: 2026-02-16 13:55:46.581441

"""

from typing import Sequence, Union
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes
from alembic import op
from langboard_shared.core.db.ColumnTypes import CSVType, EnumLikeType, SnowflakeIDType
from langboard_shared.core.routing.ApiErrorCode import ApiErrorCode
from langboard_shared.domain.models.ApiKeySetting import ApiKeyProvider
from langboard_shared.domain.models.UserSignInHistory import SignInErrorCode


# revision identifiers, used by Alembic.
revision: str = "40cf298bc4f2"
down_revision: Union[str, None] = "ca34731e2432"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_key_setting",
        sa.Column("id", SnowflakeIDType, nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("user_id", SnowflakeIDType, nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("value", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("provider", EnumLikeType(ApiKeyProvider), nullable=False),
        sa.Column("ip_whitelist", CSVType(str), nullable=False),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_in_days", sa.Integer(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("api_key_setting", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_api_key_setting_user_id"), ["user_id"], unique=False)

    op.create_table(
        "mcp_tool_group",
        sa.Column("id", SnowflakeIDType, nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("user_id", SnowflakeIDType, nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tools", CSVType(str), nullable=False),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_sign_in_history",
        sa.Column("id", SnowflakeIDType, nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("user_id", SnowflakeIDType, nullable=False),
        sa.Column("is_success", sa.Boolean(), nullable=False),
        sa.Column("ip_address", sa.TEXT(), nullable=True),
        sa.Column("error_code", EnumLikeType(SignInErrorCode), nullable=True),
        sa.Column("signed_in_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user_sign_in_history", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_sign_in_history_user_id"), ["user_id"], unique=False)

    op.create_table(
        "api_key_usage",
        sa.Column("id", SnowflakeIDType, nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("api_key_id", SnowflakeIDType, nullable=True),
        sa.Column("endpoint", sa.TEXT(), nullable=False),
        sa.Column("method", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("is_success", sa.Boolean(), nullable=False),
        sa.Column("ip_address", sa.TEXT(), nullable=True),
        sa.Column("used_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["api_key_id"], ["api_key_setting.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("api_key_usage", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_api_key_usage_api_key_id"), ["api_key_id"], unique=False)

    op.create_table(
        "mcp_tool_group_usage",
        sa.Column("id", SnowflakeIDType, nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("tool_group_id", SnowflakeIDType, nullable=False),
        sa.Column("user_id", SnowflakeIDType, nullable=True),
        sa.Column("bot_id", SnowflakeIDType, nullable=True),
        sa.Column("execution_time_ms", sa.Float(), nullable=False),
        sa.Column("is_success", sa.Boolean(), nullable=False),
        sa.Column("error_code", EnumLikeType(ApiErrorCode), nullable=True),
        sa.Column("executed_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["bot_id"], ["bot.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tool_group_id"], ["mcp_tool_group.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_email"), ["email"], unique=False)

    with op.batch_alter_table("user_email", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_email_email"), ["email"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_email", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_email_email"))

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_email"))

    op.drop_table("mcp_tool_group_usage")
    with op.batch_alter_table("api_key_usage", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_api_key_usage_api_key_id"))

    op.drop_table("api_key_usage")
    with op.batch_alter_table("user_sign_in_history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_sign_in_history_user_id"))

    op.drop_table("user_sign_in_history")
    op.drop_table("mcp_tool_group")
    with op.batch_alter_table("api_key_setting", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_api_key_setting_user_id"))

    op.drop_table("api_key_setting")
    # ### end Alembic commands ###
