"""empty message

Revision ID: 82f4e1fbed04
Revises: ddab3d9bf214
Create Date: 2026-03-18 10:29:25.986616

"""

from typing import Sequence, Union
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes
from alembic import op
from langboard_shared.core.db.ColumnTypes import EnumLikeType, SnowflakeIDType
from langboard_shared.domain.models.UserIdentityLink import IdentityProvider


# revision identifiers, used by Alembic.
revision: str = "82f4e1fbed04"
down_revision: Union[str, None] = "ddab3d9bf214"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_identity_link",
        sa.Column("id", SnowflakeIDType, nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("user_id", SnowflakeIDType, nullable=False),
        sa.Column("provider", EnumLikeType(IdentityProvider), nullable=False),
        sa.Column("external_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("issuer", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "external_id", name="uq_user_identity_link_provider_external_id"),
        sa.UniqueConstraint("user_id", "provider", name="uq_user_identity_link_user_provider"),
    )
    with op.batch_alter_table("user_identity_link", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_identity_link_external_id"), ["external_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_user_identity_link_provider"), ["provider"], unique=False)
        batch_op.create_index(batch_op.f("ix_user_identity_link_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_identity_link", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_identity_link_user_id"))
        batch_op.drop_index(batch_op.f("ix_user_identity_link_provider"))
        batch_op.drop_index(batch_op.f("ix_user_identity_link_external_id"))

    op.drop_table("user_identity_link")
    # ### end Alembic commands ###
