const API = {
    AUTH: {
        EMAIL: "/auth/email",
        SIGN_IN: "/auth/signin",
        SIGN_OUT: "/auth/signout",
        REFRESH: "/auth/refresh",
        ABOUT_ME: "/auth/me",
        RECOVERY: {
            SEND_LINK: "/auth/recovery/send",
            VALIDATE: "/auth/recovery/validate",
            RESET: "/auth/recovery/reset",
        },
        SIGN_UP: {
            SEND_LINK: "/auth/signup",
            ACTIVATE: "/auth/signup/activate",
            EXISTS_EMAIL: "/auth/signup/exist/email",
            RESEND_LINK: "/auth/signup/resend",
        },
    },
    ACCOUNT: {
        GET_SUBEMAILS: "/account/subemails",
        UPDATE_PROFILE: "/account/profile",
        CHANGE_PASSWORD: "/account/password",
        UPDATE_PREFERRED_LANGUAGE: "/account/preferred-language",
        EMAIL: {
            CRUD: "/account/email",
            VERIFY: "/account/email/verify",
        },
        USER_GROUP: {
            CREATE: "/account/group",
            CHANGE_NAME: "/account/group/{group_uid}/name",
            UPDATE_ASSIGNED_EMAILS: "/account/group/{group_uid}/emails",
            DELETE: "/account/group/{group_uid}",
        },
    },
    BATCH: "/batch",
    NOTIFICATION: {
        GET_LIST: "/notifications",
        SETTINGS: {
            ALL: "/notification/settings/all",
            TYPE: "/notification/settings/type",
            ALL_PROJECT: "/notification/settings/project",
            PROJECT: "/notification/settings/project/{uid}",
            ALL_COLUMN: "/notification/settings/column",
            COLUMN: "/notification/settings/project/{uid}/column/{project_column_uid}",
            ALL_CARD: "/notification/settings/card",
            CARD: "/notification/settings/project/{uid}/card/{card_uid}",
            ALL_WIKI: "/notification/settings/wiki",
            WIKI: "/notification/settings/project/{uid}/wiki/{wiki_uid}",
        },
    },
    ACTIVITIY: {
        USER: "/activity/user",
        PROJECT: "/activity/project/{uid}",
        PROJECT_COLUMN: "/activity/project/{uid}/column/{project_column_uid}",
        CARD: "/activity/project/{uid}/card/{card_uid}",
        PROJECT_WIKI: "/activity/project/{uid}/wiki/{wiki_uid}",
    },
    DASHBOARD: {
        ALL_STARRED_PROJECTS: "/dashboard/user/projects/starred",
        PROJECTS: "/dashboard/projects",
        TOGGLE_STAR_PROJECT: "/dashboard/projects/{uid}/star",
        CREATE_PROJECT: "/dashboard/projects/new",
        CARDS: "/dashboard/cards",
        TRACKING: "/dashboard/tracking",
    },
    BOARD: {
        GET: "/board/{uid}",
        DETAILS: "/board/{uid}/details",
        GET_INVITATION: "/project/invite/details/{token}",
        IS_AVAILABLE: "/board/{uid}/available",
        IS_PROJECT_ASSIGNEE: "/board/{uid}/is-assigned/{assignee_uid}",
        GET_CARDS: "/board/{uid}/cards",
        UPDATE_ASSIGNED_USERS: "/board/{uid}/assigned-users",
        UNASSIGN_ASSIGNEE: "/board/{uid}/unassign/{assignee_uid}",
        ACCEPT_INVITATION: "/project/invite/accept",
        DECLINE_INVITATION: "/project/invite/decline",
        CHAT: {
            GET_SESSIONS: "/board/{uid}/chat/sessions",
            GET_MESSAGES: "/board/{uid}/chat/session/{session_uid}",
            UPDATE_SESSION: "/board/{uid}/chat/session/{session_uid}",
            DELETE_SESSION: "/board/{uid}/chat/session/{session_uid}",
            UPLOAD: "/board/{uid}/chat/upload",
            TEMPLATE: {
                GET_LIST: "/board/{uid}/chat/templates",
                CREATE: "/board/{uid}/chat/template",
                UPDATE: "/board/{uid}/chat/template/{template_uid}",
                DELETE: "/board/{uid}/chat/template/{template_uid}",
            },
        },
        COLUMN: {
            CREATE: "/board/{uid}/column",
            CHANGE_NAME: "/board/{uid}/column/{project_column_uid}/name",
            CHANGE_ORDER: "/board/{uid}/column/{project_column_uid}/order",
            DELETE: "/board/{uid}/column/{project_column_uid}",
        },
        CARD: {
            CREATE: "/board/{uid}/card",
            CHANGE_ORDER: "/board/{uid}/card/{card_uid}/order",
            GET_DETAILS: "/board/{uid}/card/{card_uid}",
            CHANGE_DETAILS: "/board/{uid}/card/{card_uid}/details",
            UPDATE_ASSIGNED_USERS: "/board/{uid}/card/{card_uid}/assigned-users",
            UPDATE_LABELS: "/board/{uid}/card/{card_uid}/labels",
            UPDATE_RELATIONSHIPS: "/board/{uid}/card/{card_uid}/relationships",
            ARCHIVE: "/board/{uid}/card/{card_uid}/archive",
            DELETE: "/board/{uid}/card/{card_uid}",
            ATTACHMENT: {
                UPLOAD: "/board/{uid}/card/{card_uid}/attachment",
                CHANGE_NAME: "/board/{uid}/card/{card_uid}/attachment/{attachment_uid}/name",
                CHANGE_ORDER: "/board/{uid}/card/{card_uid}/attachment/{attachment_uid}/order",
                DELETE: "/board/{uid}/card/{card_uid}/attachment/{attachment_uid}",
            },
            COMMENT: {
                GET_LIST: "/board/{uid}/card/{card_uid}/comments",
                ADD: "/board/{uid}/card/{card_uid}/comment",
                UPDATE: "/board/{uid}/card/{card_uid}/comment/{comment_uid}",
                DELETE: "/board/{uid}/card/{card_uid}/comment/{comment_uid}",
                REACT: "/board/{uid}/card/{card_uid}/comment/{comment_uid}/react",
            },
            CHECKLIST: {
                CREATE: "/board/{uid}/card/{card_uid}/checklist",
                NOTIFY: "/board/{uid}/card/{card_uid}/checklist/{checklist_uid}/notify",
                CHANGE_TITLE: "/board/{uid}/card/{card_uid}/checklist/{checklist_uid}/title",
                CHANGE_ORDER: "/board/{uid}/card/{card_uid}/checklist/{checklist_uid}/order",
                TOGGLE_CHECKED: "/board/{uid}/card/{card_uid}/checklist/{checklist_uid}/toggle-checked",
                DELETE: "/board/{uid}/card/{card_uid}/checklist/{checklist_uid}",
            },
            CHECKITEM: {
                CREATE: "/board/{uid}/card/{card_uid}/checklist/{checklist_uid}/checkitem",
                CHANGE_TITLE: "/board/{uid}/card/{card_uid}/checkitem/{checkitem_uid}/title",
                CHANGE_ORDER: "/board/{uid}/card/{card_uid}/checkitem/{checkitem_uid}/order",
                CHANGE_STATUS: "/board/{uid}/card/{card_uid}/checkitem/{checkitem_uid}/status",
                TOGGLE_CHECKED: "/board/{uid}/card/{card_uid}/checkitem/{checkitem_uid}/toggle-checked",
                CARDIFY: "/board/{uid}/card/{card_uid}/checkitem/{checkitem_uid}/cardify",
                DELETE: "/board/{uid}/card/{card_uid}/checkitem/{checkitem_uid}",
            },
            SUB_CHECKITEM: {
                CREATE: "/board/{uid}/card/{card_uid}/checkitem/{checkitem_uid}/sub-checkitem",
                CHANGE_ORDER: "/board/{uid}/card/{card_uid}/sub-checkitem/{sub_checkitem_uid}/order",
            },
        },
        WIKI: {
            GET_ALL: "/board/{uid}/wikis",
            GET_DETAILS: "/board/{uid}/wiki/{wiki_uid}",
            CREATE: "/board/{uid}/wiki",
            UPLOAD: "/board/{uid}/wiki/{wiki_uid}/attachment",
            CHANGE_DETAILS: "/board/{uid}/wiki/{wiki_uid}/details",
            CHANGE_ORDER: "/board/{uid}/wiki/{wiki_uid}/order",
            CHANGE_PUBLIC: "/board/{uid}/wiki/{wiki_uid}/public",
            UPDATE_ASSIGNEES: "/board/{uid}/wiki/{wiki_uid}/assignees",
            DELETE: "/board/{uid}/wiki/{wiki_uid}",
        },
        BOT: {
            SCOPE: {
                CREATE: "/board/{uid}/bot/{bot_uid}/scope",
                TOGGLE_TRIGGER_CONDITION: "/board/{uid}/scope/{scope_uid}/trigger-condition",
                DELETE: "/board/{uid}/scope/{scope_uid}",
            },
            SCHEDULE: {
                GET_ALL_BY_CARD: "/board/{uid}/bot/{bot_uid}/card/{card_uid}/schedules",
                GET_ALL_BY_COLUMN: "/board/{uid}/bot/{bot_uid}/column/{project_column_uid}/schedules",
                SCHEDULE: "/board/{uid}/bot/{bot_uid}/schedule",
                RESCHEDULE: "/board/{uid}/bot/{bot_uid}/reschedule/{schedule_uid}",
                UNSCHEDULE: "/board/{uid}/bot/{bot_uid}/unschedule/{schedule_uid}",
            },
            LOG: {
                GET_ALL_BY_CARD: "/board/{uid}/bot/{bot_uid}/card/{card_uid}/logs",
                GET_ALL_BY_COLUMN: "/board/{uid}/bot/{bot_uid}/column/{project_column_uid}/logs",
            },
        },
        SETTINGS: {
            UPDATE_DETAILS: "/board/{uid}/settings/details",
            UPDATE_USER_ROLES: "/board/{uid}/settings/roles/user/{user_uid}",
            DELETE_PROJECT: "/board/{uid}/settings/delete",
            LABEL: {
                CREATE: "/board/{uid}/settings/label",
                CHANGE_DETAILS: "/board/{uid}/settings/label/{label_uid}/details",
                CHANGE_ORDER: "/board/{uid}/settings/label/{label_uid}/order",
                DELETE: "/board/{uid}/settings/label/{label_uid}",
            },
            INTERNAL_BOT: {
                CHANGE_BOT: "/board/{uid}/settings/internal-bot",
                CHANGE_SETTINGS: "/board/{uid}/settings/internal-bot/settings",
            },
        },
    },
    METADATA: {
        CARD: "/metadata/project/{uid}/card/{card_uid}",
        PROJECT_WIKI: "/metadata/project/{uid}/wiki/{wiki_uid}",
    },
    SETTINGS: {
        IS_AVAILABLE: "/settings/available",
        GET_ALL: "/settings/all",
        GET: "/settings/app/{uid}",
        CREATE: "/settings/app",
        UPDATE: "/settings/app/{uid}",
        DELETE: "/settings/app/{uid}",
        DELETE_SELECTED: "/settings/app",
        USERS: {
            GET_LIST: "/settings/users",
            CREATE: "/settings/users",
            UPDATE: "/settings/users/{user_uid}",
            DELETE: "/settings/users/{user_uid}",
            DELETE_SELECTED: "/settings/users",
        },
        BOTS: {
            CREATE: "/settings/bot",
            UPDATE: "/settings/bot/{bot_uid}",
            GENERATE_NEW_API_TOKEN: "/settings/bot/{bot_uid}/new-api-token",
            DELETE: "/settings/bot/{bot_uid}",
        },
        GLOBAL_RELATIONSHIPS: {
            CREATE: "/settings/global-relationship",
            UPDATE: "/settings/global-relationship/{uid}",
            DELETE: "/settings/global-relationship/{uid}",
            DELETE_SELECTED: "/settings/global-relationship",
        },
        INTERNAL_BOTS: {
            CREATE: "/settings/internal-bot",
            UPDATE: "/settings/internal-bot/{bot_uid}",
            CHANGE_DEFAULT: "/settings/internal-bot/{bot_uid}/default",
            DELETE: "/settings/internal-bot/{bot_uid}",
        },
        SCHEMAS: {
            API_LIST: "/schema/api",
        },
        OLLAMA: {
            GET_LIST: "/settings/ollama/models",
            GET_DETAILS: "/settings/ollama/model/details",
            GET_RUNNING_LIST: "/settings/ollama/models/running",
        },
    },
    GLOBAL: {
        INTERNAL_BOTS: {
            GET: "/global/internal-bot/{bot_uid}",
        },
    },
} as const;

export const Routing = {
    API,
} as const;
