export const DATA_TEXT_FORMAT_DESCRIPTIONS = {
    audio: "Audio url format: <audio src='audio_url' />",
    date: "Date format: <date>yyyy-MM-dd</date>",
    file: "File url format: <file name='filename' src='file_url' />",
    mention: "User mention format: [**@user_or_bot_name**](user_or_bot_uid)",
    image: "Image url format: ![alt_text](image_url)",
    video: "Video url format: <video src='video_url' />",
    plant_uml: "Plant UML format: $$PlantUml\nplant_uml_code\n$$",
    graphviz: "Graphviz format: $$Graphviz\ngraphviz_code\n$$",
    flowchart: "Flowchart format: $$Flowchart\nflowchart_code\n$$",
    mermaid: "Mermaid format: $$Mermaid\nmermaid_code\n$$",
    equation: "Equation format: $$\nmath_code\n$$",
    inline_equation: "Inline equation format: $$math_code$$",
    internal_link: "Internal link format as obsidian syntax: [[card_or_project_wiki:card_or_wiki_id]]\nExample: [[card:...]], [[project_wiki:...]]",
};
